name: build gocrypt agent image

on:
  release:
    types: [created]

jobs:
  build_gocrypt_agent:
    defaults:
      run:
        working-directory: gocrypt/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Release
      run: make build-release

    - uses: actions/upload-artifact@v2
      with:
        name: gocrypt-agent-linux
        path: gocrypt/gocrypt
