name: make gocrypt release

on:
  push:
    branches: [main]

jobs:
  build_gocrypt_agent:
    defaults:
      run:
        working-directory: gocrypt/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Release
      run: make build-release

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ~/work/gocrypt/gocrypt/gocrypt
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: rsheasby/gocrypt:latest

    - id: bump
      uses: zwaldowski/match-label-action@v1
      with:
        allowed: major,minor,patch

    - uses: zwaldowski/semver-release-action@v1
      with:
        bump: ${{ steps.bump.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
