name: build gocrypt agent image

on:
  release:
    types: [created]

jobs:
  build_gocrypt_agent_image:
    defaults:
      run:
        working-directory: gocrypt/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: gocrypt-agent
        
    - name ls
      run: ls
    
