name: gocrypt agent

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test Dev
      run: make test

    - name: Test Release
      run: make test-release
      
    - name: Lint
      run: make lint
