name: gocrypt agent

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_gocrypt_agent:
    defaults:
      run:
        working-directory: gocrypt/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test Dev
      run: make test

    - name: Test Release
      run: make test-coverage
      
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -E gosec -E gofmt --timeout 5m -v

    - name: Build Dev
      run: make build

    - name: Build Release
      run: make build-release
      
    - uses: actions/upload-artifact@v2
      with:
        name: gocrypt-agent
        path: gocrypt/gocrypt
