name: make gocrypt release

on:
  push:
    branches: [main]

jobs:
  make_gocrypt_release:
    defaults:
      run:
        working-directory: gocrypt/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Release
      run: make build-release

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - id: release
      uses: zwaldowski/semver-release-action@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true 
      with:
        bump: patch
        github_token: ${{ secrets.GITHUB_TOKEN }}
        prefix: v
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: gocrypt/
        platforms: linux/amd64
        push: true
        tags: |
          rsheasby/gocrypt:latest
          rsheasby/gocrypt:${{ steps.release.outputs.version }}
