name: test gocrypt

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build_gocrypt_agent:
    defaults:
      run:
        working-directory: gocrypt/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test Dev
      run: make test

    - name: Test Release
      run: make test-coverage
      
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -E gosec -E gofmt --timeout 5m -v

    - name: Build Dev
      run: make build

    - name: Build Release
      run: make build-release
  
  test_gocrypt_client:
    runs-on: ubuntu-latest
    needs: [build_gocrypt_agent]
    services:
      redis:
        image: redis:latest
        ports: [6379]
    
    steps: 
    - name: Start gocrypt agent
      run: ls -la
